### ISSUE TITLE
Startpage won't load if Javascript is disabled

### ISSUE THREAD

**Issue by ch0ccyra1n** [miawinter98/Wave#1]
If I disable Javascript in the browser, the startpage gets stuck loading.

![the startpage for Wave is stuck loading forever](https://github.com/miawinter98/Wave/assets/121838894/04ca91b0-4172-4bed-8c7a-1bfb116849b3)

**Comment by miawinter98** [comment]
Well, Wave is build in the SPA framework Blazor, with the Startpage using it's interactive render feature to display that loading page while the Server is processing the articles available, it will also allow it to dynamically load more articles after a button press (infinite scrolling would also be possible, but that's not nice). 
Of course a scriptless implementation would be possible, but it would make programming that page a lot harder, worsen the user experience since loading more articles would require full page reloads, and also makes using a framework like Blazor redundant...

**Comment by miawinter98** [comment]
This has now been fixed with the release of 1.0.0-alpha.3. 

In the end it's still smoother with JS thanks to Blazors enhanced navigation, but the end user can now also use the page without it. I made it a principal now that everything reachable by an unauthenticated user should also work statically. This of course, or rather I recently realized, will improve SEO.
